name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  check:
    runs-on: ${{ matrix.runs-on.labels }}
    strategy:
      matrix:
        runs-on:
          - labels: [ubuntu-latest]
            system: x86_64-linux
          - labels: [self-hosted, linux, ARM64]
            system: aarch64-linux
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v7
      - uses: DeterminateSystems/magic-nix-cache-action@v2
        if: ${{ matrix.runs-on.system != 'aarch64-linux' }}
        #TODO: aarch64-linux build is crashing the runner
      - run: nix build .#amazonImage -L --system ${{ matrix.runs-on.system }}
        if: ${{ matrix.runs-on.system != 'aarch64-linux' }}
      - run: nix flake check -L --system ${{ matrix.runs-on.system }}
        if: ${{ matrix.runs-on.system != 'aarch64-linux' }}
