name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  check:
    runs-on: ${{ matrix.runs-on.labels }}
    strategy:
      matrix:
        runs-on:
          - labels: [ubuntu-latest]
            system: x64_64-linux
          - labels: [self-hosted, linux, ARM64]
            system: aarch64-linux
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v7
      - uses: DeterminateSystems/magic-nix-cache-action@v2
        if: ${{ matrix.runs-on.system != 'aarch64-linux' }}
      - run: nix flake check -L
